spring:
  application:
    name: SpringServer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    defer-datasource-initialization: true # data.sql 실행을 테이블 생성이후로 지연

  sql:
    init:
      mode: always
      data-locations: classpath:/center.sql

  jwt:
    secret: ${JWT_SECRET}

  cloud:
    aws:
      s3:
        bucket: ${BUCKET_NAME}
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ${S3_REGION}
      cloudfront:
        domain: ${CLOUDFRONT_DOMAIN}

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

springdoc:
  show-login-endpoint: true