spring:
  application:
    name: SpringServer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdb
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    defer-datasource-initialization: true # data.sql 실행을 테이블 생성이후로 지연https://petstore.swagger.io/v2/swagger.json

  sql:
    init:
      mode: always

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    secret: qo0ZNtzizpcWq/E+Ou/FN8rcYDaycVNolSpOYhIPOOM=

springdoc:
  show-login-endpoint: true

logging:
  level:
    org.springframework.data.redis: DEBUG
jasypt:
  encryptor:
    password: gyoe-tae-secret-key