spring:
  application:
    name: SpringServer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(ABqPb8zpG5FCvSB2CiqLc0svq0Qmh7Wkgk1wYlJJEqMi3sULrdp1Hd2XrLsL6tK2Gnt2SW9nv49Rj86I1ftb13LmdPhd19BM4plbeTrnznna7Q/eIr7gwhJ4n5JuyfzW)
    username: ENC(LAdrT9uRSsMhF4WuzP6tzA==)
    password: ENC(KSYbLcCjwq/F1TbfbmCynM5ew6gkNvnV)

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    defer-datasource-initialization: true # data.sql 실행을 테이블 생성이후로 지연

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:/center.sql

  jwt:
    secret: ENC(fEW9/KVmH73bRYEzWACc3XE2lzVFPAzaMe3u4yTzEw3vgZk6jYl5B+rg8aDTp/nxUxujp+LjEu4=)

  cloud:
    aws:
      s3:
        bucket: ENC(TqagxcbY8dcPk7yURJJS7Bt/fpMtGSewYO4EL9zN4vk=)
      credentials:
        access-key: ENC(y57+i+X1IooRBH0htxAJl/I4tZFRj5rx8bCvRXnSRFk=)
        secret-key: ENC(WuXYKG9PuSVhWNNe1CJC1647zBo45Pf1NGLUanwuto92DPLrB6yYyhd/hIOt6HT1tObxgUHN/kQ=)
      region:
        static: ENC(fMHjyzCwi3ATMG9kd2/YioF7Oi3gW5gf)
      cloudfront:
        domain: ENC(gWYrw5ePeq3a8oKIbKbjBo0NAX3LGsW30tEpvQQTx6fPTPyZcQ09QQ==)

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

springdoc:
  show-login-endpoint: true

jasypt:
  encryptor:
    key: ${JASYPT_SECRET_KEY}